apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <html>
    <head><title>NGINX V1</title></head>
    <body>
      <h1>ðŸš€ this pradeep gupta</h1>
      <p>Image: nginx:latest</p>
      <p>Deployed via Argo CD</p>
    </body>
    </html>
